services:
  postgres:
    image: postgres:17
    container_name: iam-guardian-postgres
    environment:
      POSTGRES_DB: iamguardian
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: iam-guardian-keycloak
    command: start-dev --import-realm
    depends_on:
      - postgres
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/iamguardian
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres

      KC_HTTP_PORT: 8080
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import

volumes:
  postgres_data: