spring.application.name=IAM Guardian
server.port=8080

iamguardian.keycloak.base-url=http://localhost:8081
iamguardian.keycloak.realm=iam-guardian-demo
iamguardian.keycloak.admin-realm=master
iamguardian.keycloak.client-id=admin-cli
iamguardian.keycloak.username=admin
iamguardian.keycloak.password=admin