spring:
  application:
    name: iam-guardian

  datasource:
    url: jdbc:postgresql://localhost:5432/iamguardian
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/iam-guardian-demo
server:
  port: 8080

iamguardian:
  keycloak:
    server-url: http://localhost:8081
    realm: iam-guardian-demo
    admin-realm: master
    admin-client-id: admin-cli
    admin-username: admin
    admin-password: admin